# Generated by Django 4.1 on 2022-11-03 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thai_name_station', models.CharField(max_length=64)),
                ('eng_name_station', models.CharField(max_length=64)),
                ('code_station', models.CharField(max_length=64)),
                ('station_detail', models.TextField()),
            ],
        ),
    ]
