# Generated by Django 4.1 on 2022-11-11 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bts_for_fun', '0002_stationdetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tourist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thai_name_tourist', models.CharField(max_length=200)),
                ('eng_name_tourist', models.CharField(max_length=200)),
                ('tourist_detail', models.TextField()),
                ('comment', models.TextField()),
                ('rating', models.SmallIntegerField(default=0)),
                ('on_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='on_id_station', to='bts_for_fun.station')),
            ],
        ),
    ]
