# Generated by Django 4.1 on 2022-11-11 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bts_for_fun', '0004_touristdetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='touristdetail',
            name='t_detail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='t_details', to='bts_for_fun.station'),
        ),
    ]
