# Generated by Django 4.1.1 on 2022-11-19 07:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bts_for_fun', '0008_station_station_pic_tourist_tourist_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tourist',
            name='rating',
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=0)),
                ('tourist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bts_for_fun.tourist')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
