# Generated by Django 4.1 on 2022-11-20 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bts_for_fun', '0009_remove_tourist_rating_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='station',
            name='stt_pic',
        ),
        migrations.RemoveField(
            model_name='tourist',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='tourist',
            name='t_pic',
        ),
    ]
