# Generated by Django 4.1 on 2022-11-20 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bts_for_fun', '0010_remove_station_stt_pic_remove_tourist_comment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='station',
            name='station_detail',
        ),
        migrations.AddField(
            model_name='station',
            name='station_detail_exit',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='station',
            name='station_detail_plan',
            field=models.TextField(blank=True),
        ),
    ]
